name = "DiffEqSensitivity"
uuid = "41bf760c-e81c-5289-8e54-58b1f1f8abe2"
authors = ["Christopher Rackauckas <accounts@chrisrackauckas.com>"]
version = "5.1.3"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DiffEqDiffTools = "01453d9d-ee7c-5054-8395-0335cb756afa"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[compat]
DataFrames = "0.19, 0.20"
DiffEqBase = "6.5"
DiffEqCallbacks = "2.9"
DiffEqDiffTools = "1.4"
FFTW = "1.2"
ForwardDiff = "0.10"
GLM = "1.3"
Parameters = "0.12"
QuadGK = "2.1"
RecursiveArrayTools = "1.0"
Tracker = "0.2"
ZygoteRules = "0.2"
julia = "1"

[extras]
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["OrdinaryDiffEq", "Calculus", "ReverseDiff", "Distributions", "SafeTestsets", "Test", "QuasiMonteCarlo", "Random", "Pkg"]
